debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: debug
    org:
      hibernate:
        SQL: info
  org.hibernate.type.descriptor.sql.BasicBinder: trace


spring:
  datasource:
    url: jdbc:mysql://localhost:3306/board
    username: root
    password: admin
    driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      defer-datasource-initialization: true
      hibernate.ddl-auto: create
      open-in-view: false
      show-sql: true
      properties:
        hibernate.format_sql: true
        hibernate.default_batch_fetch_size: 100

        h2.console.enabled: true
        sql.init.mode: always

        data.reset:
          base-path: /api
          detection-strategy: annotated


---

#spring:
#  config.activate.on-cloud-platform: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#    sql.init.mode: always
#    test.database.replace: none

