debug: false
management.endpoints.web.exposure.include: "*"

logging:
  level:
    com.fastcampus.projectboard: debug
    org.springframework.web.servlet: info
    org:
      hibernate:
        SQL: debug
        type.descriptor.sql.BasicBinder: trace
#        type:
#          descriptor:
#            sql: trace


spring:
    thymeleaf3:
      decoupled-logic: true

#  config.activate.on-profile: default
    datasource:
      url: jdbc:mysql://localhost:3306/board
      username: root
      password: admin
      driver-class-name: com.mysql.cj.jdbc.Driver

    jpa:
      defer-datasource-initialization: true
#      hibernate.ddl-auto: create
      hibernate.ddl-auto: validate
      open-in-view: false

      properties:
        hibernate:
          show_sql: true
          format_sql: true
          default_batch_fetch_size: 100
          use_sql_comments: true

        h2.console.enabled: true
        sql.init.mode: always

    data.rest:
      base-path: /api
      detection-strategy: annotated

    thymeleaf:
      cache: false
      enabled: true
      prefix: classpath:/templates/
      suffix: .html

---
spring:
    config:
      activate:
        on-profile: h2-dev
    datasource:
      url: jdbc:h2:mem:testdb
      username: sa
      driver-class-name: org.h2.Driver

    jpa:
      defer-datasource-initialization: true
#      hibernate.ddl-auto: create
      hibernate.ddl-auto: validate
      open-in-view: false
      show-sql: true
      properties:
        hibernate.show_sql: true
        hibernate.format_sql: true
        hibernate.default_batch_fetch_size: 100

        h2.console.enabled: true
        sql.init.mode: always

    data.rest:
      base-path: /api
      detection-strategy: annotated

---

#spring:
#  config:
#    activate:
#      on-profile: testdb
#  datasource:
#    url: jdbc:h2:mem:board;mode=mysql
#    driverClassName: org.h2.Driver
#    sql.init.mode: always
#    test.database.replace: none   #@AutoConfigureTestDatabase(replace = AutoConfigureTestDatabase.Replace.NONE)

